name: Push to GCR GitHub Action
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # example with Workload Identity Federation
  build-and-push-to-gcr-workload-identity:
    name: Build & push - with workload identity
    runs-on: ubuntu-latest
    permissions: # <- this section is needed for workload identity
      contents: 'read'
      id-token: 'write'
   steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: `google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
